### ISSUE TITLE
Is call to '#dup' necessary in GCStats::Middleware?

### ISSUE THREAD

**Issue by nbeyer** [cerner/gc_stats#3]
I may be missing something obvious, but I'm not understanding why GCStats::Middleware is invoking '#dup' and there's no comment to explain it. Here's the code:

```
def call(env)
  dup._call(env)
end
```

If there's not a specific reason for it, I'll post a PR to remove it.

**Comment by sambao21** [comment]
I'd like to know too. I've seen this around about how this is threadsafe from the railscast episode on rack middleware and I've looked around and it seems Sinatra does this, but I need some better explanation how.

**Comment by faizahmedshaik** [comment]
The railscast episode is where I got that info. Also this stackoverflow question - http://stackoverflow.com/questions/23028226/rack-middleware-and-thread-safety goes into it a little bit as well.

**Comment by nbeyer** [comment]
I'm going to dig into this a bit more, but I don't see why this is necessary for this middleware. The @app instance variable doesn't seem to be a concern and the other instance variables that this middleware creates are unnecessary (they aren't used in the class anywhere other than the return, so that can be elided).

Even the answer to that stackoverflow question is contradictory. It says "yes, you should dup" for the safety of instance variables created in your middleware, but the question doesn't use instance variables, so the answer seems like it should be "no, you don't need it, but might in the future if you change something".

**Comment by nbeyer** [comment]
What's the link to the railscast?

**Comment by nbeyer** [comment]
Based on what I've seen so far, the constraint seems to be that the Rack middleware instance can be invoked from multiple threads concurrently, so a middleware class needs to implement basic protection of shared data.

I must admit that the use of 'dup' is an interesting way of implementing thread safety. My gut reaction is that it's a very lazy way of doing it, as it's essentially just avoiding protecting the shared instance by creating an instance per request. This seems like it's going to create unnecessary garbage to be collected. However, I suppose there could be an argument that creating an additional object may be more efficient in Ruby than using mutexes/locks. I think that would have to be measured and evaluated quite a bit more to make such a call.

Regardless, the GCStats::Middleware doesn't need to worry about any of these things as it can be made thread safe without making duplicates or using mutexes ... it doesn't need any shared state. I'll post a pull request to formalize my suggestion.

Here are some reference issues and code I found:
- https://github.com/rack/rack/issues/558 (this seems like a nice approach for general usage)
- https://github.com/vcr/vcr/issues/58 (this doesn't seem like a good approach for general usage)

**Comment by kpshek** [comment]
Closing this issue since @nbeyer addressed this in #4
